apiVersion: apps/v1
kind: Deployment
metadata:
  name: registryweb-deployment
spec:
  selector:
    matchLabels:
      app: registryweb
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: registryweb
    spec:
      containers:
      - name: registryweb
        image: hyper/docker-registry-web
        ports:
        - containerPort: 8080
        env:
          - name: REGISTRY_URL
            value: "https://192.168.1.171:50000/v2"
          - name: REGISTRY_TRUST_ANY_SSL
            value: "true"
          - name: REGISTRY_NAME
            value: "daed.duckdns.org:50000"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: registryweb
  name: registryweb
spec:
    ports:
    - nodePort: 30880
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector: 
      app: registryweb
    type: NodePort
